[package]
name = "gem_bitcoin"
version = { workspace = true }
edition = { workspace = true }
publish = false

[features]
default = []
rpc = ["dep:chain_traits", "dep:gem_client"]
reqwest = ["gem_client/reqwest"]
integration_tests = ["rpc", "reqwest"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
primitives = { path = "../primitives" }
gem_client = { path = "../gem_client", optional = true }
chain_traits = { path = "../chain_traits", optional = true }
number_formatter = { path = "../number_formatter" }
async-trait = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
num-bigint = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
reqwest = { workspace = true }
