[package]
name = "gem_bitcoin"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
primitives = { path = "../primitives" }
gem_client = { path = "../gem_client" }
chain_traits = { path = "../chain_traits" }
number_formatter = { path = "../number_formatter" }
async-trait = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
