[package]
name = "gem_solana"
version = { workspace = true }
edition = { workspace = true }

[features]
default = ["rpc", "reqwest"]
rpc = ["gem_jsonrpc/client", "dep:async-trait", "dep:gem_client", "dep:chain_traits"]
reqwest = ["gem_jsonrpc/reqwest"]
integration = []

[dependencies]
curve25519-dalek = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
bs58 = { workspace = true }
borsh = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
num-bigint = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde_serializers = { path = "../serde_serializers" }
primitives = { path = "../primitives" }
gem_jsonrpc = { path = "../gem_jsonrpc" }

async-trait = { workspace = true, optional = true }
gem_client = { path = "../gem_client", optional = true }
chain_traits = { path = "../chain_traits", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
reqwest = { workspace = true }

[[test]]
name = "provider_token_test"
test = false
required-features = ["rpc", "reqwest"]

[[test]]
name = "provider_balances_test"
test = false
required-features = ["rpc", "reqwest"]

[[test]]
name = "provider_staking_test"
test = false
required-features = ["rpc", "reqwest"]

