[package]
name = "gem_cardano"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
primitives = { path = "../primitives" }
serde = { workspace = true, features = ["derive"] }
typeshare = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
async-trait = { workspace = true }
chain_traits = { path = "../chain_traits" }
gem_client = { path = "../gem_client" }
