[package]
name = "nft_provider"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
futures.workspace = true 
async-trait = { workspace = true }

primitives = { path = "../primitives" }
gem_evm = { path = "../gem_evm" }
gem_solana = { path = "../gem_solana", features = ["reqwest"], default-features = false }
gem_chain_rpc = { path = "../gem_chain_rpc" }