[package]
name = "swap_skip_client"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
primitives = { path = "../primitives" }
reqwest = { workspace = true }
