[package]
name = "gem_stellar"
version = { workspace = true }
edition = { workspace = true }

[features]
default = ["typeshare"]
rpc = ["dep:number_formatter", "dep:chrono", "dep:async-trait", "dep:chain_traits", "dep:urlencoding"]
typeshare = ["dep:typeshare"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
primitives = { path = "../primitives" }

# Optional dependencies for the rpc feature
number_formatter = { path = "../number_formatter", optional = true }
chrono = { workspace = true, features = ["serde"], optional = true }
async-trait = { workspace = true, optional = true }
chain_traits = { path = "../chain_traits", optional = true }
urlencoding = { workspace = true, optional = true }
typeshare = { workspace = true, optional = true }
serde_json = { workspace = true }
gem_client = { path = "../gem_client" }
