[package]
name = "gem_xrp"
version = { workspace = true }
edition = "2024"

[features]
default = []
typeshare = ["dep:typeshare"]
rpc = ["dep:chrono", "dep:reqwest-middleware", "dep:serde_serializers"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
hex = { workspace = true }
primitives = { path = "../primitives" }
number_formatter = { path = "../number_formatter" }

typeshare = { workspace = true, optional = true }

reqwest-middleware = { workspace = true, features = ["json"], optional = true }
chrono = { workspace = true, features = ["serde"], optional = true }
serde_serializers = { path = "../serde_serializers", optional = true }

