[package]
name = "gem_tracing"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3.20" }
sentry = { version = "0.42.0", features = ["tracing"] }

settings = { path = "../settings" }