name: Clippy
on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4
      
      - uses: Swatinem/rust-cache@v2

      - name: Install just
        run: cargo install just

      - name: Run Lint
        run: just lint
